# Copyright 2018, Erlang Solutions Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import logging

# import gevent
# from gevent import Greenlet
from typing import Set

from Pyrlang.Term.pid import Pid
from Pyrlang.bases import BaseNode, BaseProcess

LOG = logging.getLogger("Pyrlang")


class Process(BaseProcess):
    """ Implements Erlang process semantic and lifetime.
        Registers itself in the process registry, can receive and send messages.
        To optionally register self with a name, call
        ``node.register_name(self, term.Atom('fgsfds'))``

        Subclass the Process to run your logic in its ``_loop() -> bool``
        function or to handle incoming messages via
        ``handle_one_inbox_message(self, msg)``.

        .. note::
            Only a ``Process`` can serve as a target for sending messages, for
            linking and monitoring. You do not need to create a Process for simple
            one-way interactions with remote Erlang nodes.
    """

    def __init__(self, node: BaseNode) -> None:
        """ Create a process and register itself. Pid is generated by the node
            object.
        """
        self.engine_ = node.engine_  # type: BaseEngine
        """ Pluggable async event engine """

        self.node_name_ = node.node_name_  # type: str
        """ Convenience field to see the Node (from Node.all_nodes[name]). """

        self.inbox_ = node.engine_.queue_new()
        """ Message queue (gevent.Queue). Messages are detected by the ``_run``
            loop and handled one by one in ``handle_one_inbox_message()``. 
        """

        self.pid_ = node.register_new_process(self)
        """ Process identifier for this object. Remember that when creating a 
            process, it registers itself in the node, and this creates a
            reference. 
            References prevent an object from being garbage collected.
            To destroy a process, get rid of this extra reference by calling
            ``exit()`` and telling it the cause of its death.
        """

        self.is_exiting_ = False

        self.monitors_ = set()  # type: Set[Pid]
        """ Who monitors us. Either local or remote processes. """

        self.monitor_targets_ = set()  # type: Set[Pid]
        """ Who we monitor. """

        self.engine_.spawn(self._loop)  # greenlet has to be scheduled for run

    def _loop(self) -> bool:
        """ Returns True to continue running. False to stop. """
        self.handle_inbox()
        return not self.is_exiting_

    def handle_inbox(self):
        """ Do not override `handle_inbox`, instead go for
            `handle_one_inbox_message`
        """
        while True:
            msg = self.inbox_.get()
            if msg is None:
                break
            self.handle_one_inbox_message(msg)

    def handle_one_inbox_message(self, msg):
        """ Override this method to handle new incoming messages. """
        LOG.error("%s: Unhandled msg %s" % (self.pid_, msg))
        raise NotImplementedError()

    def exit(self, reason=None):
        """ Marks the object as exiting with the reason, informs links and
            monitors and unregisters the object from the node process
            dictionary.
        """
        # TODO: Inform links and monitors

        from Pyrlang import Node
        n = Node.all_nodes[self.node_name_]
        n.on_exit_process(self.pid_, reason)
